from .Convertor import Convertor
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from Resume_generator.user_info_module.Persone import Persone


class Convertor_person_to_pdf(Convertor):
    def convert(self, persone: Persone, file_path: str):
        c = canvas.Canvas(file_path, pagesize=A4)
        width, height = A4

        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width / 2, height - 60, f"{persone.name}")

        # Personal Info
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"Date of Birth: {persone.birthday}")

        # Contacts
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 130, "Contacts:")
        c.setFont("Helvetica", 12)
        y = height - 150
        for key, value in persone.contacts.to_dict().items():
            c.drawString(70, y, f"{key}: {value}")
            y -= 16

        # Skills
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y - 10, "Skills:")
        y -= 30
        c.setFont("Helvetica", 12)
        for skill in persone.skils.to_dict().get("skills", []):
            c.drawString(70, y, f"• {skill}")
            y -= 16

        # Experience
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y - 10, "Work Experience:")
        y -= 30
        c.setFont("Helvetica", 12)
        exp= persone.experience.to_dict()
        for key, value in exp.items():
            role = value.get('role', '')
            company = key
            description = value.get('description', '')
            years = value.get('duration', '')
            c.drawString(70, y, f"{role} at {company} ({years}) - {description}")
            y -= 16

        # Education
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y - 10, "Education:")
        y -= 30
        c.setFont("Helvetica", 12)
        edu= persone.education.to_dict()
        for key, value in edu.items():
            degree = value.get('degree', '')
            institution = key
            field = value.get('field', '')
            years = value.get('duration', '')
            c.drawString(70, y, f"{degree} in {field} from {institution} ({years})")
            y -= 16
        # Footer line
        c.setStrokeColorRGB(0.7, 0.7, 0.7)
        c.line(50, 50, width - 50, 50)
        c.setFont("Helvetica-Oblique", 10)
        c.drawCentredString(width / 2, 35, "Generated by Resume Generator")

        c.save()